# Generated by Django 5.1.1 on 2025-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='valoracion_media',
            field=models.FloatField(default=0.0),
        ),
    ]
